
- id: yard_lights_on
  alias: Yard Lights On Timer
  trigger:
  - event: sunset
    offset: +00:00:00
    platform: sun
  action:
  - data:
      entity_id: group.lights_yard
    service: homeassistant.turn_on
  - data:
      entity_id: switch.patio_sec1
    service: switch.turn_off

- id: yard_lights_off
  alias: Yard Lights Off Timer
  trigger:
  - event: sunrise
    offset: -01:00:00
    platform: sun
  - at: '23:55:00'
    platform: time
  - at: 02:00:00
    platform: time
  action:
  - data:
      entity_id: group.lights_yard
    service: homeassistant.turn_off
  - data:
      entity_id: switch.patio_sec1
    service: switch.turn_on

- id: pool_pump_timer
  alias: Pool Pump Timer
  trigger:
     platform: template
     value_template: "{{ states('sensor.time') == (states.input_datetime.pool_start_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  action:
     - service: script.pool_pump_run
     - service: script.pool_sweep_run

- id: pool_all_off
  alias: Pool All Off Timer
  trigger:
  - at: 00:30:00
    platform: time
  action:
  - data:
      entity_id: 
        - switch.pool_sweep
        - switch.pool_main
    service: switch.turn_off
  - data:
      entity_id: climate.pool
    service: climate.turn_off
  - data:
      entity_id: climate.pool
      temperature: 32
    service: climate.set_temperature

- id: rear_patio_sprinklers
  alias: Rear Patio Sprinklers Timer
  trigger:
     platform: template
     value_template: "{{ states('sensor.time') == (states.input_datetime.rear_patio_start_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
     condition: and
     conditions:
        - condition: state
          entity_id: sensor.rear_patio_watering_day
          state: 'True'
        - condition: state
          entity_id: sensor.rain_72h
          state: '0.0'
  action:
  - service: script.rear_patio_sprinklers

- id: flower_box_sprinklers
  alias: Flower Box Sprinklers Timer
  trigger:
     platform: template
     value_template: "{{ states('sensor.time') == (states.input_datetime.flower_box_start_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
     condition: and
     conditions:
        - condition: state
          entity_id: sensor.flower_box_watering_day
          state: 'True'
        - condition: state
          entity_id: sensor.rain_72h
          state: '0.0'
  action:
  - service: script.flower_box_sprinklers

- id: front_yard_sprinklers
  alias: Front Yard Sprinklers Timer
  trigger:
     platform: template
     value_template: "{{ states('sensor.time') == (states.input_datetime.front_yard_start_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
     condition: and
     conditions:
        - condition: state
          entity_id: sensor.front_yard_watering_day
          state: 'True'
        - condition: state
          entity_id: sensor.rain_72h
          state: '0.0'
  action:
  - service: script.front_yard_sprinklers

- id: heater_night_timer
  alias: Heater Night Timer
  trigger:
  - at: '23:45:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: climate.house
      temperature: 62
    service: climate.set_temperature

- id: heater_evening_timer
  alias: Heater Evening Timer
  trigger:
  - at: '17:30:00'
    platform: time
  condition: []
  action:
  - alias: ''
    data:
      entity_id: climate.house
      temperature: 68
    service: climate.set_temperature

- id: heater_weekday_timer
  alias: Heater Weekday Timer
  trigger:
  - at: 06:45:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: climate.house
      temperature: 65
    service: climate.set_temperature

- id: heater_midmorn_timer
  alias: Heater Mid Morning Timer
  trigger:
  - at: '10:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: climate.house
      temperature: 67
    service: climate.set_temperature

- id: heater_weekend_timer
  alias: Heater Weekend Timer
  trigger:
  - at: 07:45:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - data:
      entity_id: climate.house
      temperature: 65
    service: climate.set_temperature

- id: dcare_arm
  alias: Day Care Bell Arm Timer
  trigger:
  - at: '08:00:00'
    platform: time
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: input_boolean.dcare_bell
    service: input_boolean.turn_on

- id: dcare_disarm
  alias: Day Care Bell Disarm Timer
  trigger:
  - at: '17:30:00'
    platform: time
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: input_boolean.dcare_bell
    service: input_boolean.turn_off

- id: night_arm
  alias: Night Alarm Arm Timer
  trigger:
  - at: 01:30:00
    platform: time
  action:
  - data:
      entity_id: input_boolean.night_alarm
    service: input_boolean.turn_on

- id: night_disarm
  alias: Night Alarm Disarm Timer
  trigger:
  - at: 06:30:00
    platform: time
  action:
  - data:
      entity_id: input_boolean.night_alarm
    service: input_boolean.turn_off

- id: kitch_speaker_down
  alias: Kitchen Speaker Down Timer
  trigger:
  - at: '13:30:00'
    platform: time
  - at: '22:00:00'
    platform: time
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
    - data:
        entity_id: media_player.kitchen_speaker
        volume_level: 0.05
      service: media_player.volume_set

- id: kitchen_speaker_up
  alias: Kitchen Speaker Up Timer
  trigger:
  - at: '08:00:00'
    platform: time
  - at: '16:00:00'
    platform: time
  action:
    - data:
        entity_id: media_player.kitchen_speaker
        volume_level: 0.50
      service: media_player.volume_set

- id: fans_off
  alias: Fans Off Timer
  trigger:
  - at: '01:00:00'
    platform: time
  action:
  - data:
      entity_id: fans.auto_fans
    service: homeassistant.turn_off

- id: fountain_on
  alias: Fountain On
  trigger:
  - at: '09:00:00'
    platform: time
  action:
  - data:
      entity_id: switch.patio_fountain
    service: homeassistant.turn_on

- id: fountain_off
  alias: Fountain Off
  trigger:
  - at: '22:00:00'
    platform: time
  action:
  - data:
      entity_id: switch.patio_fountain
    service: homeassistant.turn_off

