- id: yard_lights_on
  alias: Yard Lights On Timer
  trigger:
  - event: sunset
    offset: +00:00:00
    platform: sun
  action:
  - data:
      entity_id:
      - switch.gate_light
      - switch.entry_light
      - switch.yard_lights1
      - switch.patio_lights
      - switch.yard_lights2
      - switch.gate_light
      - switch.xmas_lights
      - switch.pool_light
      - switch.gate_light
    service: switch.turn_on
  - data:
      entity_id: switch.patio_sec1
    service: switch.turn_off
- id: yard_lights_off
  alias: Yard Lights Off Timer
  trigger:
  - event: sunrise
    offset: -01:00:00
    platform: sun
  - at: '23:55:00'
    platform: time
  - at: 02:00:00
    platform: time
  action:
  - data:
      entity_id:
      - switch.gate_light
      - switch.entry_light
      - switch.yard_lights1
      - switch.patio_lights
      - switch.yard_lights2
      - switch.gate_light
      - switch.xmas_lights
      - switch.pool_light
      - switch.gate_light
    service: switch.turn_off
  - data:
      entity_id: switch.patio_sec1
    service: switch.turn_on
- id: pool_main_off
  alias: Pool Main Off Timer
  trigger:
  - at: 00:30:00
    platform: time
  - at: '16:15:00'
    platform: time
  action:
  - data:
      entity_id: switch.pool_main
    service: switch.turn_off
  - data:
      entity_id: climate.pool
    service: climate.turn_off
  - data:
      entity_id: climate.pool
      temperature: 32
    service: climate.set_temperature
- id: pool_main_on
  alias: Pool Main On Timer
  trigger:
  - at: '12:00:00'
    platform: time
  action:
  - data:
      entity_id: switch.pool_main
    service: switch.turn_on
- id: pool_sweep_on
  alias: Pool Sweep On Timer
  trigger:
  - at: '12:30:00'
    platform: time
  action:
  - data:
      entity_id: switch.pool_sweep
    service: switch.turn_on
- id: pool_sweep_off
  alias: Pool Sweep Off Timer
  trigger:
  - at: '15:00:00'
    platform: time
  action:
  - data:
      entity_id: switch.pool_sweep
    service: switch.turn_off
- id: '1541799676159'
  alias: Rear Patio Sprinklers Timer
  trigger:
  - at: '11:00:00'
    platform: time
  - at: '13:00:00'
    platform: time
  - at: '15:00:00'
    platform: time
  - at: '17:00:00'
    platform: time
  condition: []
  action:
  - service: script.rear_patio_sprinklers
- id: '1541800366517'
  alias: Flower Box Sprinklers Timer
  trigger:
  - at: '12:30:00'
    platform: time
  condition: []
  action:
  - service: script.flower_box_sprinklers
- id: '1541800460669'
  alias: Front Yard Sprinklers Timer
  trigger:
  - event: sunset
    offset: +01:00:00
    platform: sun
  condition: []
  action:
  - service: script.front_yard_sprinklers
- id: '1541801995724'
  alias: Heater Night Timer
  trigger:
  - at: '23:45:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: climate.house
      temperature: 62
    service: climate.set_temperature
- id: '1541802268414'
  alias: Heater Evening Timer
  trigger:
  - at: '17:45:00'
    platform: time
  condition: []
  action:
  - alias: ''
    data:
      entity_id: climate.house
      temperature: 68
    service: climate.set_temperature
- id: '1541802437123'
  alias: Heater Weekday Timer
  trigger:
  - at: 06:45:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: climate.house
      temperature: 65
    service: climate.set_temperature
- id: heater_midmorn
  alias: Heater Mid Morning Timer
  trigger:
  - at: '10:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: climate.house
      temperature: 67
    service: climate.set_temperature
- id: '1541802601105'
  alias: Heater Weekend Timer
  trigger:
  - at: 07:45:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - data:
      entity_id: climate.house
      temperature: 65
    service: climate.set_temperature
- id: dcare_arm
  alias: Day Care Bell Arm Timer
  trigger:
  - at: '08:00:00'
    platform: time
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: input_boolean.dcare_bell
    service: input_boolean.turn_on
- id: dcare_disarm
  alias: Day Care Bell Disarm Timer
  trigger:
  - at: '17:30:00'
    platform: time
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: input_boolean.dcare_bell
    service: input_boolean.turn_off
- id: night_arm
  alias: Night Alarm Arm Timer
  trigger:
  - at: 01:30:00
    platform: time
  action:
  - data:
      entity_id: input_boolean.night_alarm
    service: input_boolean.turn_on
- id: night_disarm
  alias: Night Alarm Disarm Timer
  trigger:
  - at: 06:30:00
    platform: time
  action:
  - data:
      entity_id: input_boolean.night_alarm
    service: input_boolean.turn_off
- id: kitch_speaker_down
  alias: Kitchen Speaker Down Timer
  trigger:
  - at: '13:30:00'
    platform: time
  action:
    - data:
        entity_id: media_player.kitchen_speaker
        volume_level: 0.05
      service: media_player.volume_set
- id: kitchen_speaker_up
  alias: Kitchen Speaker Up Timer
  trigger:
  - at: '08:00:00'
    platform: time
  - at: '16:00:00'
    platform: time
  action:
    - data:
        entity_id: media_player.kitchen_speaker
        volume_level: 0.40
      service: media_player.volume_set
- id: fans_off
  alias: Fans Off Timer
  trigger:
  - at: '01:00:00'
    platform: time
  action:
  - data:
      entity_id: 
      - fan.bedr_fan
      - fan.bedta_fan
      - fan.family_fan
    service: fan.turn_off
