- platform: mqtt
  name: "Gate Bell"
  state_topic: stat/gate_bell/gate_bell

- platform: mqtt
  name: "Door Bell"
  state_topic: stat/door_bell/door_bell

- platform: mqtt
  name: "Car Gate Btn"
  state_topic: stat/gate_button/gate_toggle


