
- platform: generic_thermostat
  name: House
  heater: switch.house_heat
  target_sensor: sensor.house_temperature
  away_temp: 60
  cold_tolerance: 0.3
  hot_tolerance: 1.0
  ac_mode: false
  precision: 0.1
  min_cycle_duration:
     minutes: 5
  keep_alive:
     minutes: 3

- platform: generic_thermostat
  name: Chicken Coop
  heater: switch.chicken_heat
  target_sensor: sensor.chickens_temperature
  min_temp: 32
  ac_mode: false
  precision: 0.1
  keep_alive:
     minutes: 3

- platform: generic_thermostat
  name: Camper
  heater: switch.camper_heat
  target_sensor: sensor.camper_temperature
  min_temp: 32
  ac_mode: false
  precision: 0.1
  keep_alive:
     minutes: 3

- platform: generic_thermostat
  name: Pool
  heater: switch.pool_heat
  target_sensor: sensor.pool_temperature
  hot_tolerance: 1.0
  min_temp: 32
  max_temp: 95
  ac_mode: false
  precision: 0.1
  keep_alive:
     minutes: 3

