homeassistant:
  name: Beresford
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 20
  unit_system: Imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

lovelace:
  mode: yaml

device_tracker:
   - platform: nmap_tracker
     hosts: 
       - 172.16.20.18/32 
       - 172.16.20.19/32 
     home_interval: 10

vacuum:
   - platform: roomba
     host: roomba1.amaroq.net
     name: Roomba1
     username: !secret roomba_user
     password: !secret roomba_pass

mqtt:
   broker: 127.0.0.1

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Monitor system health
system_health:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: aliska.amaroq.net:8123
   #   ssl_certificate: /amaroq/hass/config/ssl/ServerCertificate.cer
   #   ssl_key: /amaroq/hass/config/ssl/amaroq_private.key

api:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

recorder:
  purge_keep_days: 10

logger:
  default: info

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# UPS
apcupsd:

rainforest_usb:
  device: /dev/serial/by-id/usb-Rainforest_RFA-Z106-RA-PC_RAVEn_v2.3.21-if00-port0
  name: smartmeter

rfxcom_rx:
  device: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A6003Q5Y-if00-port0 

# Cloud
cloud:
  google_actions:
    filter:
      include_domains:
        - light
        - fan
        - scene
      include_entities:
        - climate.house
        - climate.pool
        - switch.speakers
        - switch.car_gate
        - switch.garage_door
        - switch.pool_main
        - switch.pool_sweep
        - switch.patio_fountain
        - switch.coop_door
        - input_boolean.dcare_bell
        - input_boolean.door_alarm
        - input_boolean.house_alarm

vera:
   vera_controller_url: http://172.16.20.22:3480
   lights: [23, 6, 72, 38, 36, 34, 32, 31, 7, 46, 71, 53, 49, 30, 52, 18, 16, 14, 15, 33, 8, 75, 77, 85, 81, 80, 88, 89, 86, 91]

# External Files
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
light: !include light.yaml
switch: !include switch.yaml
climate: !include climate.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

