
group.all_automations:
   hidden: false

group.all_fans:
   hidden: false

group.all_lights:
   hidden: false

group.all_remotes:
   hidden: false

group.all_scripts:
   hidden: false

group.all_switches:
   hidden: false

