
binary_sensor.family_motion:
   device_class: motion

binary_sensor.living_motion:
   device_class: motion

binary_sensor.master_motion:
   device_class: motion

binary_sensor.office_motion:
   device_class: motion

binary_sensor.bedr_motion:
   device_class: motion

binary_sensor.bedta_motion:
   device_class: motion

binary_sensor.garage_motion:
   device_class: motion

sensor.shed_humidity:
   device_class: humidity

sensor.camper_humidity:
   device_class: humidity

group.all_automations:
   hidden: false

group.all_fans:
   hidden: false

group.all_lights:
   hidden: false

group.all_remotes:
   hidden: false

group.all_scripts:
   hidden: false

group.all_switches:
   hidden: false

binary_sensor.ped_gate:
   icon: mdi:door

binary_sensor.garbage_gate:
   icon: mdi:door

binary_sensor.chickens_gate:
   icon: mdi:door

binary_sensor.patio_gate:
   icon: mdi:door

binary_sensor.ivy_gate:
   icon: mdi:door

binary_sensor.family_door:
   icon: mdi:door

binary_sensor.front_door:
   icon: mdi:door

binary_sensor.office_door:
   icon: mdi:door

binary_sensor.dining_door:
   icon: mdi:door

binary_sensor.kitchen_door:
   icon: mdi:door

binary_sensor.pbath_door:
   icon: mdi:door

binary_sensor.shed_door:
   icon: mdi:door

binary_sensor.garage_rdoor:
   icon: mdi:door

