
#media_player.chromefamily:
#  hidden: true 

#media_player.chromecastultra3804:
#  hidden: true 

media_player.googlehome6995:
  hidden: true 

media_player.rxv677_b95979:
  hidden: true

media_player.rxv677_b95979_zone_2:
  hidden: true

media_player.samsung_8_series_65_un65mu800d:
  hidden: true

switch.garage_heat:
  hidden: true

switch.pool_heat:
  hidden: true

switch.house_heat:
  hidden: true

switch.chicken_light:
  hidden: true

switch.camper_heat:
  hidden: true

