#- cal_id: "92fknd25pctvebjdut3h8rj3ao@group.calendar.google.com"
#entities:
#- devices_id: test_everything
#name: Give me everything
#track: true
#- devices_id: test_important
#name: Important Stuff
#track: true
#search: "#Important"
#offset: "!!"

