
lights_house:
   name: House Lights
   entities:
      - group.lights_family
      - group.lights_kitchen
      - group.lights_office
      - group.lights_dining
      - group.lights_living
      - group.lights_master
      - group.lights_bedr
      - group.lights_bedta
      - group.lights_hall
      - group.lights_shed

lights_welcome:
   name: Welcome Lights
   entities:
      - light.bookcases
      - light.family_tree
      - light.kitchen_island
      - light.living_floor
      - light.living_tree
      - light.living_mantel
      - light.short_hall
      - light.bar_light

lights_bedr:
   name: Rachel's Room
   entities:
      - light.bedr_light

lights_bedta:
   name: Amelia & Tessa's Room
   entities:
      - light.bedta_light

lights_master:
   name: Master Bedroom
   entities:
      - light.master_light

lights_living:
   name: Living Room
   entities:
      - light.living_lights
      - light.living_floor
      - light.living_tree
      - light.living_chandelier
      - light.living_entry
      - light.living_mantel

lights_dining:
   name: Dining Room
   entities:
      - light.dining_room

lights_kitchen:
   name: Kitchen
   entities:
      - light.kitchen_light
      - light.kitchen_island
      - light.kitchen_table

lights_family:
   name: Family Room
   entities:
      - light.couch_light
      - light.bookcases
      - light.bar_light
      - light.family_tree

lights_office:
   name: Office
   entities:
      - light.office_light

lights_hall:
   name: Hallway
   entities:
      - light.long_hall
      - light.short_hall

lights_shed:
   name: Shed Lights
   entities:
      - light.shed_light

lights_yard:
   name: Yard
   entities:
      - light.gate_light
      - light.yard_lights1
      - light.yard_lights2
      - light.patio_lights
      - light.dining_entry
      - light.entry_light
      - light.xmas_lights
      - light.pool_light
      - light.shed_porch

auto_fans:
   name: Auto Fans
   entities:
      - fan.bedr_fan
      - fan.bedta_fan
      - fan.family_fan

