# Input DateTime

pool_start_time:
   name: Pool Pump Start Time
   has_date: false
   has_time: true

front_yard_start_time:
   name: Front Yard Start Time
   has_date: false
   has_time: true

flower_box_start_time:
   name: Flowers Start Time
   has_date: false
   has_time: true

rear_patio_start_time:
   name: Rear Patio Start Time
   has_date: false
   has_time: true

