# Input Number
pool_pump_duration:
   name: Pool Pump Mins
   min: 60
   max: 360
   step: 15
   icon: mdi:camera-timer
   mode: box

pool_sweep_duration:
   name: Pool Sweep Mins
   min: 30
   max: 360
   step: 15
   icon: mdi:camera-timer
   mode: box

front_lawn_1_duration:
   name: Front Lawn 1 Mins
   min: 0
   max: 60
   step: 1
   icon: mdi:camera-timer
   mode: box

front_lawn_2_duration:
   name: Front Lawn 2 Mins
   min: 0
   max: 60
   step: 1
   icon: mdi:camera-timer
   mode: box

front_lawn_3_duration:
   name: Front Lawn 3 Mins
   min: 0
   max: 60
   step: 1
   icon: mdi:camera-timer
   mode: box

west_trees_duration:
   name: West Trees Mins
   min: 0
   max: 60
   step: 1
   icon: mdi:camera-timer
   mode: box

rear_patio_1_duration:
   name: Rear Patio 1 Mins
   min: 0
   max: 60
   step: 1
   icon: mdi:camera-timer
   mode: box

rear_patio_2_duration:
   name: Rear Patio 2 Mins
   min: 0
   max: 60
   step: 1
   icon: mdi:camera-timer
   mode: box

rear_patio_3_duration:
   name: Rear Patio 3 Mins
   min: 0
   max: 60
   step: 1
   icon: mdi:camera-timer
   mode: box

front_flower_box_duration:
   name: Front Flowers Mins
   min: 0
   max: 60
   step: 1
   icon: mdi:camera-timer
   mode: box

east_lawn_1_duration:
   name: East Lawn 1 Mins
   min: 0
   max: 60
   step: 1
   icon: mdi:camera-timer
   mode: box

east_lawn_2_duration:
   name: East Lawn 2 Mins
   min: 0
   max: 60
   step: 1
   icon: mdi:camera-timer
   mode: box

east_lemon_duration:
   name: East Lemon Mins
   min: 0
   max: 60
   step: 1
   icon: mdi:camera-timer
   mode: box
