# Boolean inputs
dcare_bell:
  name: Daycare Bell

night_alarm:
  name: Night Alarm

house_alarm:
  name: House Alarm

door_alarm:
  name: Door Alarm

front_yard_sunday:
  name: Sunday

front_yard_monday:
  name: Monday

front_yard_tuesday:
  name: Tuesday

front_yard_wednesday:
  name: Wednesday

front_yard_thursday:
  name: Thursday

front_yard_friday:
  name: Friday

front_yard_saturday:
  name: Saturday

flower_box_sunday:
  name: Sunday

flower_box_monday:
  name: Monday

flower_box_tuesday:
  name: Tuesday

flower_box_wednesday:
  name: Wednesday

flower_box_thursday:
  name: Thursday

flower_box_friday:
  name: Friday

flower_box_saturday:
  name: Saturday

rear_patio_sunday:
  name: Sunday

rear_patio_monday:
  name: Monday

rear_patio_tuesday:
  name: Tuesday

rear_patio_wednesday:
  name: Wednesday

rear_patio_thursday:
  name: Thursday

rear_patio_friday:
  name: Friday

rear_patio_saturday:
  name: Saturday

