
akelaamaroqnet:
  hide_if_away: false
  icon:
  mac: 70:1C:E7:9C:AB:FD
  name: akela.amaroq.net
  picture:
  track: false

scanamaroqnet:
  hide_if_away: false
  icon:
  mac: AC:18:26:53:B5:B5
  name: scan.amaroq.net
  picture:
  track: false

printamaroqnet:
  hide_if_away: false
  icon:
  mac: 6C:C2:17:25:86:04
  name: print.amaroq.net
  picture:
  track: false

homemonamaroqnet:
  hide_if_away: false
  icon:
  mac: B8:27:EB:83:59:C9
  name: homemon.amaroq.net
  picture:
  track: false

garageamaroqnet:
  hide_if_away: false
  icon:
  mac: B8:27:EB:CA:89:B7
  name: garage.amaroq.net
  picture:
  track: false

trainsetamaroqnet:
  hide_if_away: false
  icon:
  mac: B8:27:EB:04:78:9E
  name: trainset.amaroq.net
  picture:
  track: false

d85de23c7d73:
  hide_if_away: false
  icon:
  mac: D8:5D:E2:3C:7D:73
  name: d85de23c7d73
  picture:
  track: false

00a0deb95979:
  hide_if_away: false
  icon:
  mac: 00:A0:DE:B9:59:79
  name: 00a0deb95979
  picture:
  track: false

000b82d54006:
  hide_if_away: false
  icon:
  mac: 00:0B:82:D5:40:06
  name: 000b82d54006
  picture:
  track: false

c8db2609d8be:
  hide_if_away: false
  icon:
  mac: C8:DB:26:09:D8:BE
  name: c8db2609d8be
  picture:
  track: false

0c08b460a58f:
  hide_if_away: false
  icon:
  mac: 0C:08:B4:60:A5:8F
  name: 0c08b460a58f
  picture:
  track: false

0c08b461800d:
  hide_if_away: false
  icon:
  mac: 0C:08:B4:61:80:0D
  name: 0c08b461800d
  picture:
  track: false

6cadf880b28b:
  hide_if_away: false
  icon:
  mac: 6C:AD:F8:80:B2:8B
  name: 6cadf880b28b
  picture:
  track: false

388b59a18d6f:
  hide_if_away: false
  icon:
  mac: 38:8B:59:A1:8D:6F
  name: 388b59a18d6f
  picture:
  track: false

b02a438746e2:
  hide_if_away: false
  icon:
  mac: B0:2A:43:87:46:E2
  name: b02a438746e2
  picture:
  track: false

0c08b4617f90:
  hide_if_away: false
  icon:
  mac: 0C:08:B4:61:7F:90
  name: 0c08b4617f90
  picture:
  track: false

ryan_phone:
  hide_if_away: false
  consider_home: 900
  icon:
  mac: 00:9D:6B:02:8B:F5
  name: Ryan
  picture:
  track: true

steph_phone:
  hide_if_away: false
  consider_home: 900
  icon:
  mac: 90:DD:5D:6B:69:0C
  name: Stephanie
  picture:
  track: true

08f69c1e5a6a:
  hide_if_away: false
  icon:
  mac: 08:F6:9C:1E:5A:6A
  name: 08f69c1e5a6a
  picture:
  track: false

70ef00a48391:
  hide_if_away: false
  icon:
  mac: 70:EF:00:A4:83:91
  name: 70ef00a48391
  picture:
  track: false

682737deddc7:
  hide_if_away: false
  icon:
  mac: 68:27:37:DE:DD:C7
  name: 682737deddc7
  picture:
  track: false

9893ccb50889:
  hide_if_away: false
  icon:
  mac: 98:93:CC:B5:08:89
  name: 9893ccb50889
  picture:
  track: false

ec1f722e11fb:
  hide_if_away: false
  icon:
  mac: EC:1F:72:2E:11:FB
  name: ec1f722e11fb
  picture:
  track: false

macstephamaroqnet:
  hide_if_away: false
  icon:
  mac: 20:C9:D0:BE:47:0F
  name: macsteph.amaroq.net
  picture:
  track: false

ford_flex:
  hide_if_away: false
  consider_home: 900
  icon:
  mac: 50:65:83:CC:BB:67
  name: Ford Flex
  picture:
  track: true

d0c5d38ee03f:
  hide_if_away: false
  icon:
  mac: D0:C5:D3:8E:E0:3F
  name: d0c5d38ee03f
  picture:
  track: true

b8819887a37a:
  hide_if_away: false
  icon:
  mac: B8:81:98:87:A3:7A
  name: b8819887a37a
  picture:
  track: true

8cec4b8898ce:
  hide_if_away: false
  icon:
  mac: 8C:EC:4B:88:98:CE
  name: 8cec4b8898ce
  picture:
  track: true

8cec4b731747:
  hide_if_away: false
  icon:
  mac: 8C:EC:4B:73:17:47
  name: 8cec4b731747
  picture:
  track: true

7cb0c2442a73:
  hide_if_away: false
  icon:
  mac: 7C:B0:C2:44:2A:73
  name: 7cb0c2442a73
  picture:
  track: true

3880dfed76ea:
  hide_if_away: false
  icon:
  mac: 38:80:DF:ED:76:EA
  name: 3880dfed76ea
  picture:
  track: true

a4e975873a1a:
  hide_if_away: false
  icon:
  mac: A4:E9:75:87:3A:1A
  name: a4e975873a1a
  picture:
  track: true

d03169d25088:
  hide_if_away: false
  icon:
  mac: D0:31:69:D2:50:88
  name: d03169d25088
  picture:
  track: true

akelaamaroqnet_2:
  hide_if_away: false
  icon:
  mac: 54:EE:75:C3:95:32
  name: akela.amaroq.net
  picture:
  track: true

006171d03dc8:
  hide_if_away: false
  icon:
  mac: 00:61:71:D0:3D:C8
  name: 006171d03dc8
  picture:
  track: true

7c04d050ed3a:
  hide_if_away: false
  icon:
  mac: 7C:04:D0:50:ED:3A
  name: 7c04d050ed3a
  picture:
  track: true

84c9b237bb11:
  hide_if_away: false
  icon:
  mac: 84:C9:B2:37:BB:11
  name: 84c9b237bb11
  picture:
  track: true

a4e975864b74:
  hide_if_away: false
  icon:
  mac: A4:E9:75:86:4B:74
  name: a4e975864b74
  picture:
  track: true

a4e97587bca3:
  hide_if_away: false
  icon:
  mac: A4:E9:75:87:BC:A3
  name: a4e97587bca3
  picture:
  track: true

a4e975825514:
  hide_if_away: false
  icon:
  mac: A4:E9:75:82:55:14
  name: a4e975825514
  picture:
  track: true
