
akelaamaroqnet:
  hide_if_away: false
  icon:
  mac: 70:1C:E7:9C:AB:FD
  name: akela.amaroq.net
  picture:
  track: false

scanamaroqnet:
  hide_if_away: false
  icon:
  mac: AC:18:26:53:B5:B5
  name: scan.amaroq.net
  picture:
  track: false

printamaroqnet:
  hide_if_away: false
  icon:
  mac: 6C:C2:17:25:86:04
  name: print.amaroq.net
  picture:
  track: false

homemonamaroqnet:
  hide_if_away: false
  icon:
  mac: B8:27:EB:83:59:C9
  name: homemon.amaroq.net
  picture:
  track: false

garageamaroqnet:
  hide_if_away: false
  icon:
  mac: B8:27:EB:CA:89:B7
  name: garage.amaroq.net
  picture:
  track: false

trainsetamaroqnet:
  hide_if_away: false
  icon:
  mac: B8:27:EB:04:78:9E
  name: trainset.amaroq.net
  picture:
  track: false

d85de23c7d73:
  hide_if_away: false
  icon:
  mac: D8:5D:E2:3C:7D:73
  name: d85de23c7d73
  picture:
  track: false

00a0deb95979:
  hide_if_away: false
  icon:
  mac: 00:A0:DE:B9:59:79
  name: 00a0deb95979
  picture:
  track: false

000b82d54006:
  hide_if_away: false
  icon:
  mac: 00:0B:82:D5:40:06
  name: 000b82d54006
  picture:
  track: false

c8db2609d8be:
  hide_if_away: false
  icon:
  mac: C8:DB:26:09:D8:BE
  name: c8db2609d8be
  picture:
  track: false

0c08b460a58f:
  hide_if_away: false
  icon:
  mac: 0C:08:B4:60:A5:8F
  name: 0c08b460a58f
  picture:
  track: false

0c08b461800d:
  hide_if_away: false
  icon:
  mac: 0C:08:B4:61:80:0D
  name: 0c08b461800d
  picture:
  track: false

6cadf880b28b:
  hide_if_away: false
  icon:
  mac: 6C:AD:F8:80:B2:8B
  name: 6cadf880b28b
  picture:
  track: false

388b59a18d6f:
  hide_if_away: false
  icon:
  mac: 38:8B:59:A1:8D:6F
  name: 388b59a18d6f
  picture:
  track: false

b02a438746e2:
  hide_if_away: false
  icon:
  mac: B0:2A:43:87:46:E2
  name: b02a438746e2
  picture:
  track: false

0c08b4617f90:
  hide_if_away: false
  icon:
  mac: 0C:08:B4:61:7F:90
  name: 0c08b4617f90
  picture:
  track: false

ryan_phone:
  hide_if_away: false
  icon:
  mac: 00:9D:6B:02:8B:F5
  name: Ryan
  picture:
  track: true

