
front_yard_sprinklers:
  alias: Front Yard Sprinklers Running
  sequence:
  - alias: West Trees On
    data:
      entity_id: switch.west_trees
    service: switch.turn_on
  - delay: "00:{{ states('input_number.west_trees_duration')|int }}:00"
  - alias: West Tress Off
    data:
      entity_id: switch.west_trees
    service: switch.turn_off
  - delay: 00:00:10
  - alias: East Lemon On
    data:
      entity_id: switch.east_lemon
    service: switch.turn_on
  - delay: "00:{{ states('input_number.east_lemon_duration')|int }}:00"
  - alias: East Lemon Off
    data:
      entity_id: switch.east_lemon
    service: switch.turn_off
  - delay: 00:00:10
  - alias: Front Lawn 1 On
    data:
      entity_id: switch.front_lawn_1
    service: switch.turn_on
  - delay: "00:{{ states('input_number.front_lawn_1_duration')|int }}:00"
  - alias: Front Lawn 1 Off
    data:
      entity_id: switch.front_lawn_1
    service: switch.turn_off
  - delay: 00:00:10
  - alias: Front Lawn 2 On
    data:
      entity_id: switch.front_lawn_2
    service: switch.turn_on
  - delay: "00:{{ states('input_number.front_lawn_2_duration')|int }}:00"
  - alias: Front Lawn 2 Off
    data:
      entity_id: switch.front_lawn_2
    service: switch.turn_off
  - delay: 00:00:10
  - alias: Front Lawn 3 On
    data:
      entity_id: switch.front_lawn_3
    service: switch.turn_on
  - delay: "00:{{ states('input_number.front_lawn_3_duration')|int }}:00"
  - alias: Front Lawn 3 Off
    data:
      entity_id: switch.front_lawn_3
    service: switch.turn_off
  - delay: 00:00:10
  - alias: East Lawn 1 On
    data:
      entity_id: switch.east_lawn_1
    service: switch.turn_on
  - delay: "00:{{ states('input_number.east_lawn_1_duration')|int }}:00"
  - alias: East Lawn 1 Off
    data:
      entity_id: switch.east_lawn_1
    service: switch.turn_off
  - delay: 00:00:10
  - alias: East Lawn 2 On
    data:
      entity_id: switch.east_lawn_2
    service: switch.turn_on
  - delay: "00:{{ states('input_number.east_lawn_2_duration')|int }}:00"
  - alias: East Lawn 2 Off
    data:
      entity_id: switch.east_lawn_2
    service: switch.turn_off

flower_box_sprinklers:
  alias: Flower Box Sprinklers Running
  sequence:
  - alias: Front Flowers On
    data:
      entity_id: switch.front_flowers
    service: switch.turn_on
  - delay: "00:{{ states('input_number.front_flowers_duration')|int }}:00"
  - alias: Front Flowers Off
    data:
      entity_id: switch.front_flowers
    service: switch.turn_off
  - delay: 00:00:10
  - alias: Rear Patio 2 On
    data:
      entity_id: switch.rear_patio_2
    service: switch.turn_on
  - delay: "00:{{ states('input_number.rear_patio_2_duration')|int }}:00"
  - alias: Rear Patio 2 Off
    data:
      entity_id: switch.rear_patio_2
    service: switch.turn_off

rear_patio_sprinklers:
  alias: Rear Patio Sprinklers Running
  sequence:
  - alias: Rear Patio 1 On
    data:
      entity_id: switch.rear_patio_1
    service: switch.turn_on
  - delay: "00:{{ states('input_number.rear_patio_1_duration')|int }}:00"
  - alias: Rear Patio 1 Off
    data:
      entity_id: switch.rear_patio_1
    service: switch.turn_off

pool_pump_run:
  alias: Pool Pump Running
  sequence:
  - alias: Pool Pump On
    data:
      entity_id: switch.pool_main
    service: switch.turn_on
  - delay: "00:{{ states('input_number.pool_pump_duration')|int - 15 }}:00"
  - alias: Heater off
    data:
      entity_id: climate.pool
    service: climate.turn_off
  - delay: 00:15:00
  - alias: Pool Pump Off
    data:
      entity_id: switch.pool_main
    service: switch.turn_off

pool_sweep_run:
  alias: Pool Sweep Running
  sequence:
  - alias: Pool Sweep On
    data:
      entity_id: switch.pool_sweep
    service: switch.turn_on
  - delay: "00:{{ states('input_number.pool_sweep_duration')|int }}:00"
  - alias: Pool Sweep Off
    data:
      entity_id: switch.pool_sweep
    service: switch.turn_off

movie_lights:
  alias: Movie Lights
  sequence:
  - alias: step1
    data:
      entity_id: 
        - light.kitchen_island
        - light.kitchen_light
        - light.kitchen_table
        - light.couch_light
        - light.bar_light
    service: light.turn_off
  - alias: step2
    data:
      entity_id: light.bookcases
      brightness_pct: 50
    service: light.turn_on

house_lights_off:
  alias: House Lights Off
  sequence:
  - alias: step1
    data:
      entity_id: group.lights_house
    service: homeassistant.turn_off
  - alias: step2
    data:
      entity_id: remote.family_room
    service: remote.turn_off

welcome_lights:
  alias: Welcome Lights
  sequence:
  - alias: step1
    data:
      entity_id: group.lights_welcome
    service: homeassistant.turn_on

