#####################################################################
### Scripts to control pool light color selection
#####################################################################
script:
  #####################################################################
  ### Pool Light - Solid Blue; Channel 8
  pool_blue:
    sequence:

  ## turn on the light
    - service: switch.turn_on
      entity_id: switch.pool_light

  ## wait before initiating the sequence
    - delay:
        seconds: 5

  ## initiate sequence - pause briefly between cycles
    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 1 - Color Cycle
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 2 - Party Mode
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 3 - Romance
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 4 - Caribbean
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 5 - Patriotic
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 6 - CA Sunset
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 7 - Royal
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 8 - Blue
    - service: switch.turn_on
      entity_id: switch.pool_light

  ## Set Pool Scene Selection to "None"
    - service: input_select.select_option
      data:
        entity_id: input_select.pool_scene
        option: "None"

  #####################################################################
  ### Pool Light - Solid Green; Channel 9
  pool_green:
    sequence:

  ## turn on the light
    - service: switch.turn_on
      entity_id: switch.pool_light

  ## wait before initiating the sequence
    - delay:
        seconds: 5

  ## initiate sequence - pause briefly between cycles
    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 1 - Color Cycle
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 2 - Party Mode
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 3 - Romance
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 4 - Caribbean
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 5 - Patriotic
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 6 - CA Sunset
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 7 - Royal
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 8 - Blue
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 9 - Green
    - service: switch.turn_on
      entity_id: switch.pool_light

  ## Set Pool Scene Selection to "None"
    - service: input_select.select_option
      data:
        entity_id: input_select.pool_scene
        option: "None"

  #####################################################################
  ### Pool Light - Solid Magenta; Channel 12
  pool_magenta:
    sequence:
  ## turn on the light
    - service: switch.turn_on
      entity_id: switch.pool_light

  ## wait before initiating the sequence
    - delay:
        seconds: 5

  ## initiate sequence - pause briefly between cycles
    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 1 - Color Cycle
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 2 - Party Mode
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 3 - Romance
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 4 - Caribbean
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 5 - Patriotic
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 6 - CA Sunset
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 7 - Royal
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 8 - Blue
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 9 - Green
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 10 - Red
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 11 - White
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 12 - Magenta
    - service: switch.turn_on
      entity_id: switch.pool_light

  ## Set Pool Scene Selection to "None"
    - service: input_select.select_option
      data:
        entity_id: input_select.pool_scene
        option: "None"

  #####################################################################
  ### Pool Light - Solid Red; Channel 10
  pool_red:
    sequence:

  ## turn on the light
    - service: switch.turn_on
      entity_id: switch.pool_light

  ## wait before initiating the sequence
    - delay:
        seconds: 5

  ## initiate sequence - pause briefly between cycles
    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 1 - Color Cycle
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 2 - Party Mode
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 3 - Romance
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 4 - Caribbean
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 5 - Patriotic
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 6 - CA Sunset
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 7 - Royal
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 8 - Blue
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 9 - Green
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 10 - Red
    - service: switch.turn_on
      entity_id: switch.pool_light

  ## Set Pool Scene Selection to "None"
    - service: input_select.select_option
      data:
        entity_id: input_select.pool_scene
        option: "None"

  #####################################################################
  ### Pool Light - Solid White; Channel 11
  pool_white:
    sequence:

  ## turn on the light
    - service: switch.turn_on
      entity_id: switch.pool_light

  ## wait before initiating the sequence
    - delay:
        seconds: 5

  ## initiate sequence - pause briefly between cycles
    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 1 - Color Cycle
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 2 - Party Mode
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 3 - Romance
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 4 - Caribbean
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 5 - Patriotic
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 6 - CA Sunset
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 7 - Royal
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 8 - Blue
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 9 - Green
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 10 - Red
    - service: switch.turn_on
      entity_id: switch.pool_light
    - delay:
        seconds: .1

    - service: switch.turn_off
      entity_id: switch.pool_light
    - delay:
        seconds: .1

  ## 11 - White
    - service: switch.turn_on
      entity_id: switch.pool_light

  ## Set Pool Scene Selection to "None"
    - service: input_select.select_option
      data:
        entity_id: input_select.pool_scene
        option: "None"
